# Generated by Django 4.2.10 on 2024-02-21 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_updated_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated_on',
        ),
    ]
