# Generated by Django 4.2.10 on 2024-03-07 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_about'),
    ]

    operations = [
        migrations.DeleteModel(
            name='About',
        ),
    ]
